
settings: !!omap

    - sample_radius:
        type: float
        range: [0.1, 100.0]
        default: 20.0
        shader_runtime: true
        label: Sample radius
        description: >
            Controls the ao sample radius, higher values produce blurrier results,
            but might cost more performance, and cause more jittering.
  
    - max_radius:
        type: float
        range: [10, 2000.0]
        default: 500.0
        label: Maximum Radius
        description: >
            Controls how far the sky ao is computed, in world space. The higher
            the maximum radius is, the further sky ao reaches, but it also reduces
            the precision.

    - resolution:
        type: power_of_two
        range: [32, 8192]
        default: 1024
        label: Resolution
        description: >
            A higher resolution provides more details, but also costs more
            performance and memory.
  
    - sample_sequence:
        type: sample_sequence
        shader_runtime: true
        dimension: 3
        default: poisson_3D_32
        label: Sample Sequence
        description: >
            Amout and Type of samples, higher values cost more performance
            but provide smoother results.
    
    - trace_steps:
        type: int
        shader_runtime: true
        range: [1, 32]
        default: 7
        label: Trace steps
        description: >
            Controls how many steps to perform for each ray.

    - ao_multiplier:
        type: float
        shader_runtime: true
        range: [0.02, 1.0]
        default: 0.5
        label: AO Multiplier
        description: >
            Controls the ao strength, higher values produce a darker ao.

    - ao_bias:
        shader_runtime: true
        type: float
        range: [0.0, 1.0]
        default: 0.0
        label: AO Bias
        description: >
            Miminum ambient occlusion term, to prevent total dark spots.

    - normal_offset:
        shader_runtime: true
        type: float
        range: [0.0, 2.0]
        default: 0.15
        label: Normal offset
        description: >
            Moves the sky ao a bit along the pixel normals, to avoid self intersection.
        
    - noise_amount:
        shader_runtime: true
        type: float
        range: [0.0, 1.0]
        default: 0.05
        label: Noise amount
        description: >
            Improves sky ao quality by adding noise, but might lead to artifacts during
            movement.

    - blend_factor:
        type: float
        shader_runtime: true
        range: [0.01, 0.5]
        default: 0.05
        label: Border Blending
        description: >
            Controls how smooth the sky ao fades out at distance (the maximum radius)

    - border_fade:
        type: float
        range: [0.01, 0.3]
        default: 0.06
        shader_runtime: true
        label: Border Fade
        description: >
            Fades out the SkyAO term at the borders, to avoid artifacts
            with temporal resolve. If you don't use the history buffer, you can
            set this fairly low.

    - capture_height:
        type: float
        range: [10, 1500.0]
        default: 500.0
        label: Capture height
        description: >
            Controls from which height the sky ao is captured. This should be the
            height of your highest object, e.g. maximum terrain height.



daytime_settings:
