
# Render Pipeline Plugin Configuration
# Instead of editing this file, prefer to use the Plugin Configurator
# Any formatting and comments will be lost

enabled:
    - ao
    - smaa
    # - temporal_aa
    # - bloom
    # - clouds
    # - color_correction
    # - dof
    # - env_probes
    # - forward_shading
    # - fxaa
    # - motion_blur
    # - pssm
    # - scattering
    # - skin_shading
    # - sky_ao
    # - ssr
    # - volumetrics
    # - vxgi


overrides:
    ao:
        blur_quality: LOW
        occlusion_strength: 2.5
        border_fade: 0.05
        clip_length: 4
        enable_small_scale_ao: True
        sc_occlusion_strength: 0.5
        sc_occlusion_range: 7.5
        sc_occlusion_max_dist: 0.25
        technique: SSAO
        ssao_sample_radius: 50.0
        ssao_sequence: halton_3D_16
        ssao_bias: 0.0333
        ssao_max_distance: 4.0
        hbao_sample_radius: 100.0
        hbao_ray_count: 4
        hbao_ray_steps: 3
        hbao_tangent_bias: 0.65
        hbao_max_distance: 11.5
        ssvo_sequence: halton_2D_8
        ssvo_sphere_radius: 18.0
        ssvo_max_distance: 0.82
        alchemy_sample_radius: 100.0
        alchemy_sequence: halton_2D_8
        alchemy_max_distance: 3.0
        ue4ao_sample_radius: 110.5
        ue4ao_sample_sequence: halton_2D_8
        ue4ao_max_distance: 1.87

    bloom:
        num_mipmaps: 6
        bloom_strength: 4.22
        remove_fireflies: False
        lens_dirt_factor: 0.1286

    clouds:
        raymarch_steps: 160

    color_correction:
        tonemap_operator: exponential2
        reinhard_version: rgb
        exponential_factor: 1.53
        uc2t_shoulder_strength: 0.3352
        uc2t_linear_strength: 0.5339
        uc2t_linear_angle: 0.1797
        uc2t_toe_strength: 0.3919
        uc2t_toe_numerator: 0.0029
        uc2t_toe_denumerator: 0.2787
        uc2t_reference_white: 10.05
        vignette_strength: 0.0
        film_grain_strength: 0.2143
        color_lut: film_luts/default_lut.png
        use_chromatic_aberration: True
        chromatic_aberration_strength: 0.3219
        chromatic_aberration_samples: 2
        manual_camera_parameters: False
        min_exposure_value: 0.01
        max_exposure_value: 1.0
        exposure_scale: 1.0
        brightness_adaption_rate: 3.6
        darkness_adaption_rate: 0.7
        use_sharpen: False
        sharpen_strength: 0.5
        sharpen_twice: False

    dof:
        focal_point: 0.0
        focal_size: 546.875
        blur_strength: 0.0
        near_blur_strength: 0.4286

    env_probes:
        probe_resolution: 128
        diffuse_probe_resolution: 2
        max_probes: 25
        max_probes_per_cell: 25

    forward_shading:

    fxaa:
        quality: ultra
        subpixel_quality: 0.5
        edge_threshold: 0.166
        min_threshold: 0.833

    motion_blur:
        num_camera_samples: 6
        camera_blur_factor: 0.4
        enable_object_blur: False
        blur_factor: 0.5
        tile_size: 32
        max_blur_radius: 10.0
        num_samples: 12

    pssm:
        max_distance: 189.44
        logarithmic_factor: 3.0
        sun_distance: 100.0
        split_count: 4
        resolution: 1024
        border_bias: 0.058
        use_pcf: True
        filter_sequence: halton_2D_32
        filter_radius: 0.7
        fixed_bias: 0.11429
        slope_bias: 0.0
        normal_bias: 0.67
        use_pcss: False
        pcss_sequence: halton_2D_16
        pcss_penumbra_size: 2.38
        pcss_min_penumbra_size: 7.0
        use_distant_shadows: True
        dist_shadow_resolution: 4096
        dist_shadow_clipsize: 17598.28
        dist_shadow_sundist: 10050.0
        scene_shadow_resolution: 512
        scene_shadow_sundist: 300.0

    scattering:
        scattering_method: eric_bruneton
        ground_reflectance: 0.1
        rayleigh_factor: 1.0
        rayleigh_height_scale: 8.0
        mie_height_scale: 1.3
        mie_phase_factor: 0.5885
        beta_mie_scattering: 4.0
        atmosphere_start: 271.88
        enable_godrays: True
        godrays_max_samples: 128
        godrays_resolve_history: 3
        godrays_strength: 0.3

    skin_shading:
        quality: medium
        blur_scale: 0.43

    sky_ao:
        sample_radius: 20.0
        max_radius: 500.0
        resolution: 1024
        sample_sequence: poisson_3D_32
        trace_steps: 7
        ao_multiplier: 0.37
        ao_bias: 0.0
        normal_offset: 0.15
        noise_amount: 0.05
        blend_factor: 0.05
        border_fade: 0.06
        capture_height: 500.0

    smaa:
        smaa_quality: ultra

    ssr:
        effect_scale: 1.0
        trace_steps: 64
        history_length: 16
        abort_on_object_infront: True
        intial_bias: 0.1
        hit_tolerance: 0.1
        roughness_fade: 0.72
        skip_invalid_samples: False
        border_fade: 0.005

    temporal_aa:
        jitter_pattern: halton16
        history_length: 16
        jitter_amount: 1.0
        post_sharpen_amount: 1.0

    volumetrics:
        enable_volumetric_shadows: True
        volumetric_shadow_intensity: 7.13
        volumetric_shadow_brightness: 0.1
        volumetric_shadow_pow: 1.03
        volumetric_max_distance: 79.41429
        volumetric_shadow_fadein_distance: 9.49
        volumetric_num_steps: 128

    vxgi:
        grid_resolution: 256
        grid_ws_size: 100.0
        diffuse_cone_steps: 32
        specular_cone_steps: 150

