
# This file contains all available debug modes.
# You can add or remove debug modes here, aswell as
# disable or enable them, whatever fits to you.

# NOTICE: This file only has effect if debugging is enabled
# in the pipeline.yaml (settings.pipeline.display_debuger == True)

# Usually you don't have to touch this file, except when developing
# new plugins or adding new features.

render_modes:
